import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Building2, Check, ClipboardCheck, Globe2, HeartHandshake, Plane, ShieldCheck, UsersRound, Wrench } from "lucide-react";
import { Button, Disclaimer, PageHero } from "@/components/ui";
import { EmployerCTA, ProofBar } from "@/components/page-sections";
import { markets } from "@/content/site";

export const metadata={title:"About Topway",description:"Understand Topway's licensed recruitment capability, workforce categories, markets and accountable leadership."};

const workerGroups=[
 {title:"Skilled workers",icon:Wrench,copy:"Technical and experienced people assessed against role-specific requirements.",roles:["Engineers","Technicians","Electricians","Drivers","Chefs"]},
 {title:"Semi-skilled workers",icon:ClipboardCheck,copy:"Operational workers screened for relevant experience and employer expectations.",roles:["Construction workers","Warehouse staff","Hospitality staff","Production workers","Maintenance workers"]},
 {title:"General workers",icon:UsersRound,copy:"General and support workforce sourced against confirmed employer requirements.",roles:["Factory workers","Cleaners","Helpers","Operational staff","General labour"]},
 {title:"Domestic workers",icon:HeartHandshake,copy:"Household support recruitment handled with clear expectations and candidate dignity.",roles:["Domestic helpers","Caregivers","Nannies","Household cooks","Household drivers"]},
];

const primaryMarkets=markets.filter(x=>x.status==="Primary market");
const expansionMarkets=markets.filter(x=>x.status!=="Primary market");

export default function Page(){return <><PageHero eyebrow="Why Topway" title="A licensed recruitment partner built for international employers." copy="Topway helps companies define workforce requirements, review relevant Sri Lankan candidates and coordinate the path from selection to mobilisation."/><ProofBar/>
 <section className="about-decision"><div className="container about-decision-grid"><div><span className="eyebrow">Make an informed decision</span><h2>Know the capability, markets and people behind your recruitment partner.</h2><p>Topway combines employer-led selection with structured candidate coordination and verifiable licence information.</p><div className="actions"><Button href="/employers">Request Workers</Button><Button href="/licence-compliance" variant="secondary">Verify Licence</Button></div></div><div className="about-proof-console"><div className="about-proof-head"><ShieldCheck/><div><span>Licensed operation</span><strong>Foreign Employment Agency No. 2238</strong></div></div>{[["Employer requirement","Roles, numbers and terms define the campaign",BriefcaseBusiness],["Candidate selection","Employers retain final selection control",Check],["Mobilisation support","Selected-worker processing is coordinated",Plane]].map(([t,c,I]:any)=><article key={t}><I/><div><strong>{t}</strong><span>{c}</span></div></article>)}</div></div></section>
 <section className="about-workforce"><div className="container"><div className="about-section-heading"><div><span className="eyebrow">Workers we recruit</span><h2>Recruit across four workforce levels.</h2></div><p>Every campaign begins with the employer&apos;s confirmed roles, experience requirements, workforce numbers and employment terms.</p></div><div className="about-workforce-grid">{workerGroups.map(({title,icon:Icon,copy,roles},i)=><article key={title}><div className="about-card-head"><Icon/><span>{String(i+1).padStart(2,"0")}</span></div><h3>{title}</h3><p>{copy}</p><div>{roles.map(x=><span key={x}>{x}</span>)}</div><Link href="/recruitment-services">Explore recruitment support <ArrowRight/></Link></article>)}</div><div className="about-industry-link"><Building2/><div><strong>Need an industry-specific workforce?</strong><span>Review recruitment capability across construction, hospitality, manufacturing, logistics, facilities and more.</span></div><Link href="/industries">Explore industries <ArrowRight/></Link></div></div></section>
 <section className="about-markets"><div className="container about-markets-grid"><div className="about-market-intro"><span className="eyebrow">Countries we support</span><h2>Primary relationships and carefully managed expansion.</h2><p>Saudi Arabia and Qatar receive primary-market focus. Other destinations are approached only against confirmed employer demand and relevant approvals.</p><Button href="/global-markets" variant="light">Explore All Countries</Button></div><div className="about-market-board"><div className="market-board-group primary"><span>Primary markets</span>{primaryMarkets.map(x=><Link href={`/global-markets/${x.slug}`} key={x.slug}><Globe2/><div><strong>{x.name}</strong><small>{x.region}</small></div><ArrowRight/></Link>)}</div><div className="market-board-group"><span>Developing & strategic expansion</span><div className="market-chip-grid">{expansionMarkets.map(x=><Link href={`/global-markets/${x.slug}`} key={x.slug}>{x.name}<small>{x.status}</small></Link>)}</div></div></div></div><div className="container"><Disclaimer/></div></section>
 <section className="about-leadership"><div className="container"><div className="about-section-heading"><div><span className="eyebrow">Accountable leadership</span><h2>Know who is responsible for Topway.</h2></div><p>Leadership remains visible so employers know who is accountable for company direction, recruitment standards and market development.</p></div><div className="about-leadership-grid"><article><Image src="/assets/azzam.jpeg" width={700} height={700} alt="Azzam Muhammedh, Chairman and Licensee"/><div><span>Chairman and Licensee</span><h3>Azzam Muhammedh</h3><p>Provides strategic direction and oversees recruitment standards, employer relationships, candidate operations and company governance.</p><strong>Governance · Recruitment standards</strong></div></article><article><Image src="/assets/shiham.png" width={700} height={700} alt="Shiham Samsudeen, Director Marketing"/><div><span>Director – Marketing</span><h3>Shiham Samsudeen</h3><p>Leads employer engagement, digital positioning, market development and international partnership growth.</p><strong>Employer engagement · Market development</strong></div></article></div><div className="about-leadership-action"><BadgeCheck/><span>Leadership profiles and company information remain available for employer verification.</span><Link href="/leadership">View leadership profiles <ArrowRight/></Link></div></div></section>
 <section className="about-next-step"><div className="container"><span className="eyebrow">Choose your next step</span><h2>Assess Topway, then start with a clear workforce requirement.</h2><div>{[["Review our recruitment services","Understand sourcing, screening and mobilisation support.","/recruitment-services"],["Explore countries and industries","Check market positioning and workforce capability.","/global-markets"],["Share your workforce requirement","Tell Topway the roles, numbers and target timing.","/employers"]].map(([t,c,h],i)=><Link key={t} href={h}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{t}</strong><small>{c}</small></div><ArrowRight/></Link>)}</div></div></section><EmployerCTA/></>}
