import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Check, ClipboardCheck, ExternalLink, FileCheck2, HeartHandshake, MessageCircle, Plane, Search, SearchCheck, ShieldCheck, UserCheck, UsersRound } from "lucide-react";
import { Button, Disclaimer, SectionHead } from "@/components/ui";
import { MarketCard } from "@/components/cards";
import { contact, markets } from "@/content/site";
import { getOfficialJobs } from "@/lib/slbfe";

const featuredMarkets=["saudi-arabia","qatar","romania","serbia"].map(slug=>markets.find(x=>x.slug===slug)!).filter(Boolean);
export default async function Home(){const official=await getOfficialJobs();const available=official.jobs.reduce((sum,x)=>sum+x.available,0);return <>
 <section className="home-hero"><div className="container home-hero-grid"><div className="home-hero-copy"><span className="hero-label"><BadgeCheck size={15}/> Licensed overseas recruitment company in Sri Lanka</span><h1>Recruit dependable people from Sri Lanka.</h1><p>Topway helps international employers source, assess and mobilise skilled, semi-skilled, general and domestic workers through one structured recruitment process.</p><div className="actions"><Button href="/employers">Request Workers</Button><Button href="/recruitment-process" variant="secondary">See How Recruitment Works</Button></div><div className="hero-assurance"><span><ShieldCheck/>Licence No. 2238</span><span><Check/>Employer-led selection</span><span><Check/>Responsible recruitment</span></div></div><div className="recruitment-board" aria-label="Recruitment workflow from employer requirement to mobilisation"><div className="board-head"><div><span>Employer requirement</span><strong>Technical & operational workforce</strong></div><span className="board-status">Structured process</span></div><div className="candidate-flow"><div className="source-pool"><span>Source</span>{["Skills","Experience","Role fit"].map(x=><i key={x}>{x}</i>)}</div><div className="flow-arrow"><span/><ArrowRight/></div><div className="shortlist"><span>Verified shortlist</span>{[1,2,3].map(x=><i key={x}><UserCheck size={15}/><b/><Check size={13}/></i>)}</div></div><div className="board-stages">{[["Define","01"],["Screen","02"],["Select","03"],["Mobilise","04"]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong><i/></div>)}</div></div></div></section>
 <section className="assurance-strip" aria-label="Topway capabilities"><div className="container">{[["Licensed recruitment company",ShieldCheck],["Skilled to domestic recruitment",UsersRound],["Candidate screening",ClipboardCheck],["Mobilisation support",Plane]].map(([t,I]:any)=><div key={t}><I/><span>{t}</span></div>)}</div></section>
 <section className="journey-gateway"><div className="container gateway-grid"><Link href="/employers" className="gateway-employer"><span>For international companies</span><h2>Build your workforce through one accountable partner.</h2><p>Share the roles, numbers and timeline. Topway will structure the recruitment plan around your requirement.</p><strong>Hire workers from Sri Lanka <ArrowRight/></strong><div className="gateway-route"><i/><i/><i/><i/></div></Link><div className="gateway-candidate"><span>For candidates</span><h2>Find verified opportunities and register safely.</h2><p>Check official SLBFE job orders before submitting your interest.</p><div><Link href="/job-registry">View Verified Jobs <ArrowRight/></Link><Link href="/candidates">Candidate Centre</Link></div></div></div></section>
 <section className="section categories-section"><div className="container"><SectionHead eyebrow="Recruitment categories" title="The people your operation needs." copy="Topway sources each workforce category against the employer's confirmed role, experience and selection criteria."/><div className="category-grid">{[["Skilled","Engineers, technicians, drivers, electricians and chefs.",SearchCheck],["Semi-skilled","Construction, warehouse, hospitality, production and maintenance workers.",UsersRound],["General & domestic","Domestic helpers, caregivers, nannies and household drivers.",HeartHandshake]].map(([t,c,I]:any)=><article key={t}><I/><h3>{t}</h3><p>{c}</p><Link href="/recruitment-services">Explore recruitment <ArrowRight size={15}/></Link></article>)}</div></div></section>
 <section className="section employer-benefits"><div className="container benefit-layout"><div><span className="eyebrow">Employer outcomes</span><h2 className="title">One clear workflow instead of fragmented recruitment.</h2><p className="lead">Topway organises sourcing, screening, interviews and mobilisation around the employer's decisions.</p><Button href="/employers">Request Workers</Button></div><div className="benefit-list">{[["One accountable recruitment partner",BriefcaseBusiness],["Structured candidate screening",SearchCheck],["Clear interview coordination",UserCheck],["Documentation and mobilisation support",FileCheck2]].map(([t,I]:any,i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><I/><h3>{t}</h3></article>)}</div></div></section>
 <section className="section process-section"><div className="container"><div className="process-heading"><div><span className="eyebrow">How recruitment works</span><h2 className="title">Five stages. Clear employer decisions.</h2></div><p className="lead">Topway coordinates the process while the employer retains control over requirements and final selection.</p></div><div className="recruitment-line">{[["01","Define",BriefcaseBusiness,"Confirm roles and numbers"],["02","Source",Search,"Reach relevant candidates"],["03","Screen",ClipboardCheck,"Review fit and documents"],["04","Select",UserCheck,"Coordinate employer decisions"],["05","Mobilise",Plane,"Support processing and travel"]].map(([n,t,I,c]:any)=><article key={n}><div className="step-node"><I/></div><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div><div className="process-action"><Button href="/recruitment-process" variant="secondary">View Complete Process</Button></div></div></section>
 <section className="official-jobs-feature"><div className="container official-jobs-grid"><div><span className="eyebrow">Verified opportunities</span><h2>Official SLBFE job orders, connected directly.</h2><p>The registry is retrieved from the official SLBFE source for Topway agency registration No. 2238 and refreshed every six hours.</p><div className="official-job-actions"><Button href="/job-registry" variant="light">View Verified Jobs</Button><Link href="/opportunities">All opportunities <ArrowRight/></Link></div></div><div className="official-job-console"><div><ShieldCheck/><span>Official registry status</span><strong>{official.error?"Source temporarily unavailable":"Connected to SLBFE"}</strong></div><div className="official-job-stats"><span><strong>{official.jobs.length}</strong>Job orders</span><span><strong>{available}</strong>Vacancies shown</span><span><strong>6h</strong>Refresh cycle</span></div><a href={official.source} target="_blank" rel="noreferrer">Open official source <ExternalLink size={14}/></a></div></div></section>
 <section className="section markets-section"><div className="container"><SectionHead eyebrow="Global markets" title="Priority and developing markets." copy="Saudi Arabia and Qatar are primary markets. Expansion markets remain subject to confirmed employer demand." action={<Button href="/global-markets" variant="secondary">Explore All Markets</Button>}/><div className="market-feature-grid">{featuredMarkets.map(x=><MarketCard key={x.slug} market={x}/>)}</div><Disclaimer/></div></section>
 <section className="section compliance-section"><div className="container compliance-grid"><div className="compliance-document"><Image src="/assets/license.jpeg" width={1600} height={1137} sizes="(max-width: 800px) 100vw, 48vw" alt="Topway Foreign Employment Agency Licence No. 2238"/><div className="document-scan"/><span><FileCheck2/> Licence document</span></div><div><span className="eyebrow">Licence & compliance</span><h2 className="title">Trust that can be verified.</h2><p className="lead">Topway operates under Sri Lanka Foreign Employment Agency Licence No. 2238. Employers and candidates can review the supplied licence directly.</p><div className="compliance-facts"><span><strong>2238</strong>Licence number</span><span><strong>11 February 2026</strong>Issue date</span></div><div className="actions"><Button href="/licence-compliance">View Licence</Button></div></div></div></section>
 <section className="final-cta"><div className="container final-cta-inner"><div><span className="eyebrow">Start an employer enquiry</span><h2>Tell us who you need.</h2><p>Share the positions, worker numbers and target timeline. Our team will contact you to confirm the requirement and next steps.</p></div><div className="final-cta-actions"><Button href="/employers" variant="light">Start an Employer Enquiry</Button><a href={`https://wa.me/${contact.mobile.replace("+","")}`}><MessageCircle size={17}/>WhatsApp Topway</a></div></div></section>
 </>}
