"use client";
import { useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
type Kind = "employer"|"candidate"|"contact";
type FormState="idle"|"sending"|"sent"|"error";
const simpleFields={
 candidate:[["name","Full name","text"],["phone","Phone / WhatsApp","tel"],["email","Email","email"],["location","Current location","text"],["country","Preferred country","text"],["position","Preferred position","text"],["experience","Work experience","text"],["passport","Passport status","text"],["message","Additional information","textarea"]],
 contact:[["name","Name","text"],["email","Email","email"],["phone","Phone","tel"],["subject","I am contacting as","text"],["message","How can we help?","textarea"]]
} as const;
const employerSteps=[
 {title:"Contact",copy:"Who should our recruitment team speak with?",fields:[["company","Company name","text"],["name","Contact person","text"],["country","Country","text"],["email","Email","email"],["phone","Phone or WhatsApp","tel"]]},
 {title:"Workforce requirement",copy:"Tell us about the people your operation needs.",fields:[["industry","Industry","text"],["positions","Positions required","text"],["workers","Number of workers","number"],["experience","Required experience","text"],["deployment","Target deployment date","date"]]},
 {title:"Additional information",copy:"Share the terms and documents available today.",fields:[["salary","Salary range","text"],["accommodation","Accommodation provided","text"],["transport","Transport provided","text"],["contract","Contract duration","text"],["message","Additional details","textarea"]]}
] as const;

function Field({field}:{field:readonly[string,string,string]}){const [name,label,type]=field;return <label className={type==="textarea"?"full":""}>{label}{type==="textarea"?<textarea name={name}/>:<input name={name} type={type} inputMode={type==="tel"?"tel":type==="email"?"email":type==="number"?"numeric":undefined} required={["company","name","country","email","phone","positions","workers"].includes(name)}/>}</label>}
async function send(form:HTMLFormElement,kind:Kind,setState:(x:FormState)=>void){setState("sending");const response=await fetch(`/api/${kind}`,{method:"POST",body:new FormData(form)});setState(response.ok?"sent":"error");if(response.ok){form.reset();window.dispatchEvent(new CustomEvent("topway-conversion",{detail:{event:`${kind}_form_submit`}}))}}

export function EmployerForm(){
 const [step,setStep]=useState(0),[state,setState]=useState<FormState>("idle"),[error,setError]=useState("");const formRef=useRef<HTMLFormElement>(null);
 function next(){const visible=formRef.current?.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>(`[data-step="${step}"] input,[data-step="${step}"] textarea`);const invalid=[...(visible||[])].find(x=>!x.checkValidity());if(invalid){invalid.reportValidity();setError("Complete the required fields before continuing.");return}setError("");setStep(x=>Math.min(2,x+1))}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();await send(e.currentTarget,"employer",setState)}
 if(state==="sent")return <div className="form-success" role="status"><Check/><h3>Workforce requirement received.</h3><p>Thank you. Topway has received your workforce requirement and will contact you to discuss the next steps.</p><button className="btn btn-secondary" onClick={()=>{setState("idle");setStep(0)}}>Submit another requirement</button></div>;
 return <form ref={formRef} className="form employer-form" onSubmit={submit} noValidate><input name="website" tabIndex={-1} autoComplete="off" className="honeypot"/><div className="form-progress" aria-label={`Step ${step+1} of 3`}><span>Step {step+1} of 3</span><div>{employerSteps.map((x,i)=><i key={x.title} className={i<=step?"active":""}/>)}</div></div><div className="form-step-head"><span>{employerSteps[step].title}</span><p>{employerSteps[step].copy}</p></div>{employerSteps.map((group,i)=><fieldset data-step={i} key={group.title} hidden={i!==step}><legend className="sr-only">{group.title}</legend><div className="form-grid">{group.fields.map(field=><Field key={field[0]} field={field}/>) }{i===2&&<label className="full">Job description or demand letter<input type="file" name="job_description" accept=".pdf,.doc,.docx"/></label>}</div></fieldset>)}{error&&<p className="form-error" role="alert">{error}</p>}{state==="error"&&<p className="form-error" role="alert">We could not send this right now. Check attachments are under 5 MB, or email info@topway.lk.</p>}<label className="consent" hidden={step!==2}><input type="checkbox" required/>I consent to Topway contacting me about this enquiry.</label><div className="form-controls">{step>0&&<button type="button" className="btn btn-secondary" onClick={()=>setStep(x=>x-1)}><ArrowLeft size={16}/>Back</button>}{step<2?<button type="button" className="btn btn-primary" onClick={next}>Continue<ArrowRight size={16}/></button>:<button className="btn btn-primary" disabled={state==="sending"}>{state==="sending"?"Sending…":"Submit Workforce Requirement"}<ArrowRight size={16}/></button>}</div></form>
}
export function EnquiryForm({kind="contact"}:{kind?:Kind}){const [state,setState]=useState<FormState>("idle");if(kind==="employer")return <EmployerForm/>;async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();await send(e.currentTarget,kind,setState)}return <form className="form form-grid" onSubmit={submit}><input name="website" tabIndex={-1} autoComplete="off" className="honeypot"/>{simpleFields[kind].map(field=><Field key={field[0]} field={field}/>)}{kind==="candidate"&&<><label>CV<input type="file" name="cv" accept=".pdf,.doc,.docx"/></label><label>Passport copy<input type="file" name="passport_copy" accept=".pdf,.jpg,.jpeg,.png"/></label></>}<label className="full consent"><input type="checkbox" required/>I consent to Topway contacting me about this enquiry.</label><div className="full"><button className="btn btn-primary" disabled={state==="sending"}>{state==="sending"?"Sending…":kind==="candidate"?"Register Interest":"Send Enquiry"}</button>{state==="sent"&&<p className="form-success-inline">Thank you. Topway has received your enquiry and will contact you to discuss the next steps.</p>}{state==="error"&&<p className="form-error">We could not send this right now. Check attachments are under 5 MB, or email info@topway.lk.</p>}</div></form>}
