"use client";
import { useState } from "react";
type Kind = "employer"|"candidate"|"contact";
const fields = {
 employer:[["company","Company name"],["name","Contact person"],["country","Country"],["email","Email"],["phone","Phone / WhatsApp"],["industry","Industry"],["positions","Required positions"],["workers","Number of workers"],["deployment","Required deployment date"],["message","Workforce requirement"]],
 candidate:[["name","Full name"],["phone","Phone / WhatsApp"],["email","Email"],["location","Current location"],["country","Preferred country"],["position","Preferred position"],["experience","Work experience"],["passport","Passport status"],["message","Additional information"]],
 contact:[["name","Name"],["email","Email"],["phone","Phone"],["subject","I am contacting as"],["message","How can we help?"]]
} as const;
export function EnquiryForm({kind="contact"}:{kind?:Kind}){
 const [state,setState]=useState<"idle"|"sending"|"sent"|"error">("idle");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setState("sending");const form=new FormData(e.currentTarget);const r=await fetch(`/api/${kind}`,{method:"POST",body:form});setState(r.ok?"sent":"error");if(r.ok){e.currentTarget.reset();window.dispatchEvent(new CustomEvent("topway-conversion",{detail:{event:`${kind}_form_submit`}}))}}
 return <form className="form form-grid" onSubmit={submit}><input name="website" tabIndex={-1} autoComplete="off" style={{display:"none"}}/>{fields[kind].map(([n,l],i)=><label className={i===fields[kind].length-1?"full":""} key={n}>{l}{n==="message"?<textarea name={n} required/>:<input name={n} required={["name","email","company","positions"].includes(n)}/>}</label>)}{kind==="employer"&&<><label>Job description<input type="file" name="job_description" accept=".pdf,.doc,.docx"/></label><label>Demand letter<input type="file" name="demand_letter" accept=".pdf,.doc,.docx"/></label></>}{kind==="candidate"&&<><label>CV<input type="file" name="cv" accept=".pdf,.doc,.docx"/></label><label>Passport copy<input type="file" name="passport_copy" accept=".pdf,.jpg,.jpeg,.png"/></label></>}<label className="full"><input type="checkbox" required style={{width:"auto",marginRight:8}}/>I consent to Topway contacting me about this enquiry.</label><div className="full"><button className="btn btn-primary" disabled={state==="sending"}>{state==="sending"?"Sending…":kind==="employer"?"Submit Workforce Requirement":kind==="candidate"?"Register Interest":"Send Enquiry"}</button>{state==="sent"&&<p style={{marginTop:12,color:"#17485a"}}>Thank you. Topway has received your enquiry and will contact you to discuss the next steps.</p>}{state==="error"&&<p style={{marginTop:12,color:"#9c3636"}}>We could not send this right now. Check that attachments are under 5 MB, or email info@topway.lk.</p>}</div></form>
}
