"use client";
import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Building2, Menu, MessageCircle, Phone, Search, ShieldCheck, UserRound, X } from "lucide-react";
import { contact } from "@/content/site";
import { LanguageSelect } from "./language-provider";

const links=[["Hire Workers","/employers",BriefcaseBusiness],["Workers & Services","/recruitment-services",Building2],["Countries","/global-markets",Search],["Why Topway","/about",ShieldCheck],["Verified Jobs","/job-registry",Search],["Candidate Centre","/candidates",UserRound],["Contact","/contact",MessageCircle]] as const;

export function Header(){
 const [open,setOpen]=useState(false);const panel=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;document.body.classList.add("menu-open");const previous=document.activeElement as HTMLElement;const focusable=panel.current?.querySelectorAll<HTMLElement>("a,button");focusable?.[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false);if(e.key==="Tab"&&focusable?.length){const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",key);return()=>{document.body.classList.remove("menu-open");document.removeEventListener("keydown",key);previous?.focus()}},[open]);
 return <header className="header"><div className="utility-bar"><div className="container"><span><ShieldCheck size={13}/> Licensed Foreign Employment Agency No. 2238</span><div><a href={`tel:${contact.mobile}`}>{contact.mobileDisplay}</a><a href={`mailto:${contact.email}`}>{contact.email}</a></div></div></div><div className="container nav"><Link className="brand-link" href="/" aria-label="Topway home"><Image className="logo" src="/assets/logo.png" width={198} height={136} priority alt="Topway Private Limited"/></Link><nav className="navlinks" aria-label="Main navigation">{links.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}<LanguageSelect/><Link className="btn btn-primary" href="/employers">Request Workers<ArrowRight size={16}/></Link></nav><button className="menu-button" onClick={()=>setOpen(true)} aria-label="Open navigation" aria-expanded={open}><Menu/></button></div>{open&&<div className="mobile-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="mobile-panel" ref={panel} role="dialog" aria-modal="true" aria-label="Mobile navigation"><div className="mobile-panel-head"><Image src="/assets/logo.png" width={198} height={136} alt="Topway Private Limited"/><div><LanguageSelect/><button onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button></div></div><Link className="btn btn-primary mobile-primary" href="/employers" onClick={()=>setOpen(false)}>Request Workers<ArrowRight size={16}/></Link><nav aria-label="Mobile navigation">{links.map(([n,h,I])=><Link key={h} href={h} onClick={()=>setOpen(false)}><I/>{n}<ArrowRight size={15}/></Link>)}</nav><div className="mobile-contact-actions"><a href={`tel:${contact.mobile}`}><Phone/>Call Topway</a><a href={`https://wa.me/${contact.mobile.replace("+","")}`}><MessageCircle/>WhatsApp</a></div></div></div>}</header>
}
