import { ArrowRight, CheckCircle2, ShieldCheck, ClipboardCheck, Plane, UsersRound, MessageSquareText, SearchCheck, UserCheck, FileCheck2, AlertCircle, Building2, BriefcaseBusiness } from "lucide-react";
import { Button } from "./ui";
export function ProofBar(){return <section className="proof-bar"><div className="container">{[[ShieldCheck,"Licensed operation"],[UsersRound,"Multiple workforce levels"],[ClipboardCheck,"Structured screening"],[Plane,"Mobilisation coordination"]].map(([I,t]:any)=><div key={t}><I/><span>{t}</span></div>)}</div></section>}
export function ListSection({eyebrow,title,copy,items}:{eyebrow:string;title:string;copy?:string;items:string[]}){return <section className="inner-list-section"><div className="container inner-list-layout"><div className="inner-list-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}<div className="list-visual" aria-hidden="true"><span/><span/><span/></div></div><div className="indexed-list">{items.map((x,i)=><div className="indexed-item" key={x}><span>{String(i+1).padStart(2,"0")}</span><CheckCircle2/><h3>{x}</h3></div>)}</div></div></section>}
export function EmployerCTA(){return <section className="compact-cta"><div className="container compact-cta-inner"><div><span>Planning a recruitment project?</span><h2>Discuss your workforce requirement with Topway.</h2></div><div className="compact-cta-actions"><Button href="/employers" variant="light">Request Workers</Button><a href="/contact">Contact our team <ArrowRight size={15}/></a></div></div></section>}
export function OutcomeSection({eyebrow,title,copy,items}:{eyebrow:string;title:string;copy:string;items:[string,string][]}){return <section className="outcome-section"><div className="container"><div className="outcome-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div><div className="outcome-grid">{items.map(([t,c],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{c}</p><i/></article>)}</div></div></section>}
export function DecisionSection({eyebrow,title,copy,items,action}:{eyebrow:string;title:string;copy:string;items:[string,string][];action?:React.ReactNode}){return <section className="decision-section"><div className="container decision-layout"><div className="decision-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{copy}</p>{action}</div><div className="decision-list">{items.map(([t,c],i)=><article key={t}><div className="decision-icon"><CheckCircle2/></div><span>{String(i+1).padStart(2,"0")}</span><div><h3>{t}</h3><p>{c}</p></div></article>)}</div></div></section>}
export function ConversionJourney({eyebrow="How it works",title="A clear route from requirement to mobilisation.",steps}:{eyebrow?:string;title?:string;steps?:[string,string][]}){const data=steps||[["Define","Confirm roles, criteria, worker numbers and timing."],["Source","Build a relevant candidate pool against the brief."],["Select","Coordinate screening, interviews and employer decisions."],["Mobilise","Support selected candidates through required processing."]];const icons=[MessageSquareText,SearchCheck,UserCheck,FileCheck2];return <section className="conversion-journey"><div className="container"><div className="journey-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>Each stage moves the enquiry toward a clear employer or candidate decision.</p></div><div className="journey-track">{data.map(([t,c],i)=>{const Icon=icons[i%icons.length];return <article key={t}><div className="journey-node"><Icon/><i>{i+1}</i></div><span>Stage {String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{c}</p></article>})}</div></div></section>}
export function OperatingTerms({eyebrow,title,copy,items,tone="light"}:{eyebrow:string;title:string;copy:string;items:[string,string][];tone?:"light"|"dark"|"warning"}){const icons=[BriefcaseBusiness,UserCheck,AlertCircle];return <section className={`operating-terms operating-terms-${tone}`}><div className="container operating-terms-layout"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div><div className="operating-term-list">{items.map(([t,c],i)=>{const Icon=icons[i%icons.length];return <article key={t}><Icon/><div><strong>{t}</strong><p>{c}</p></div><span>{String(i+1).padStart(2,"0")}</span></article>})}</div></div></section>}
export function CapabilityMatrix({eyebrow,title,copy,industries,roles}:{eyebrow:string;title:string;copy:string;industries:string[];roles:string[]}){return <section className="capability-matrix"><div className="container capability-matrix-layout"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div><div className="capability-columns"><article><div><Building2/><span>Industries</span></div>{industries.map(x=><strong key={x}><CheckCircle2/>{x}</strong>)}</article><article><div><UsersRound/><span>Worker categories</span></div>{roles.map(x=><strong key={x}><CheckCircle2/>{x}</strong>)}</article></div></div></section>}
