import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Check, ChevronDown, Menu, Phone, MessageCircle, BriefcaseBusiness, UserRound, ShieldCheck, Globe2 } from "lucide-react";
import { availability, contact } from "@/content/site";

export function Button({href,children,variant="primary"}:{href:string;children:React.ReactNode;variant?:"primary"|"secondary"|"light"}) {
  return <Link className={`btn btn-${variant}`} href={href}>{children}<ArrowRight size={16}/></Link>
}
export function Header(){
  const mobileLinks:[string,string][]=[["Employers","/employers"],["Candidates","/candidates"],["Global Markets","/global-markets"],["Services","/recruitment-services"],["Industries","/industries"],["Recruitment Process","/recruitment-process"],["Domestic Recruitment","/domestic-recruitment"],["About Topway","/about"],["Leadership","/leadership"],["Licence & Compliance","/licence-compliance"],["Contact","/contact"]];
  return <header className="header"><div className="utility-bar"><div className="container"><span><ShieldCheck size={13}/> Licensed Foreign Employment Agency No. 2238</span><div><a href={`tel:${contact.mobile}`}>{contact.mobileDisplay}</a><a href={`mailto:${contact.email}`}>{contact.email}</a></div></div></div><div className="container nav"><Link href="/"><Image className="logo" src="/assets/logo.png" width={198} height={136} alt="Topway Private Limited"/></Link><nav className="navlinks" aria-label="Main navigation"><div className="nav-group"><button className="nav-trigger" type="button" aria-haspopup="true">Recruitment<ChevronDown size={13}/></button><div className="nav-dropdown mega-menu"><div className="mega-intro"><BriefcaseBusiness/><strong>Recruit from Sri Lanka</strong><span>Structured sourcing, screening and mobilisation support.</span><Link href="/employers">Start an employer enquiry <ArrowRight size={13}/></Link></div><div className="mega-links"><Link href="/recruitment-services">Recruitment Services<span>End-to-end employer support</span></Link><Link href="/industries">Industries<span>Roles by operational sector</span></Link><Link href="/domestic-recruitment">Domestic Recruitment<span>Responsible household recruitment</span></Link><Link href="/recruitment-process">Our Process<span>From requirement to mobilisation</span></Link></div></div></div><Link href="/global-markets">Global Markets</Link><Link href="/employers">Employers</Link><Link href="/candidates">Candidates</Link><div className="nav-group"><button className="nav-trigger" type="button" aria-haspopup="true">Company<ChevronDown size={13}/></button><div className="nav-dropdown company-menu"><Link href="/about">About Topway</Link><Link href="/leadership">Leadership</Link><Link href="/licence-compliance">Licence & Compliance</Link><Link href="/contact">Contact</Link></div></div><Button href="/employers">Request Workers</Button></nav><details className="mobile-toggle"><summary aria-label="Open navigation"><Menu/></summary><nav className="mobile-menu" aria-label="Mobile navigation">{mobileLinks.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}<Link href="/employers" className="btn btn-primary">Request Workers</Link></nav></details></div></header>
}
export function Footer(){
  return <><footer className="footer"><div className="container"><div className="footer-grid"><div><Image src="/assets/logo-white.png" width={150} height={105} alt="Topway Private Limited"/><p>Sri Lankan talent. Global workforce solutions.</p><p>{contact.address.join(", ")}</p></div><div><h4>Employer Solutions</h4><Link href="/recruitment-services">Recruitment Services</Link><Link href="/industries">Industries</Link><Link href="/global-markets">Global Markets</Link><Link href="/employers">Request Workers</Link></div><div><h4>Company</h4><Link href="/about">About Topway</Link><Link href="/leadership">Leadership</Link><Link href="/licence-compliance">Licence & Compliance</Link><Link href="/contact">Contact</Link></div><div><h4>Candidate Support</h4><Link href="/candidates">Candidate Guide</Link><Link href="/opportunities">Current Opportunities</Link><Link href="/privacy-policy">Privacy Policy</Link><Link href="/terms">Terms</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Topway Private Limited. All rights reserved. Foreign Employment Agency Licence No. 2238.</span><a href="https://levatahq.com" target="_blank" rel="noopener noreferrer">Designed by Levata</a></div></div></footer><div className="sticky-actions"><a href={`tel:${contact.mobile}`}><Phone size={18}/><br/>Call</a><a href={`https://wa.me/${contact.mobile.replace("+","")}`}><MessageCircle size={18}/><br/>WhatsApp</a><Link href="/employers"><BriefcaseBusiness size={18}/><br/>Employer</Link><Link href="/candidates"><UserRound size={18}/><br/>Candidate</Link></div></>
}
export function PageHero({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){
  const candidate=eyebrow.includes("Candidate"), company=["About Topway","Leadership","Licence & Compliance","Contact"].includes(eyebrow);
  const primary=candidate?["Register Interest","/candidates"]:company?["Contact Topway","/contact"]:["Request Workers","/employers"];
  const nextSteps=candidate?["Confirm current opportunities","Prepare your documents","Register your interest"]:company?["Verify our credentials","Meet the leadership team","Speak directly with Topway"]:["Share roles and worker numbers","Confirm scope with our team","Begin structured sourcing"];
  const shortcuts=candidate?[["Candidate Guide","/candidates"],["Opportunities","/opportunities"],["Markets","/global-markets"],["Contact","/contact"]]:company?[["About","/about"],["Leadership","/leadership"],["Compliance","/licence-compliance"],["Contact","/contact"]]:[["Services","/recruitment-services"],["Industries","/industries"],["Markets","/global-markets"],["Process","/recruitment-process"],["Compliance","/licence-compliance"]];
  return <><section className="page-hero"><div className="container"><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span>{eyebrow}</div><div className="page-hero-grid"><div className="page-hero-main"><span className="eyebrow">{eyebrow}</span><h1 className="display">{title}</h1><p className="lead">{copy}</p><div className="page-hero-actions"><Button href={primary[1]}>{primary[0]}</Button><Link href="/contact">Speak with Topway <ArrowRight size={14}/></Link></div></div><aside className="hero-decision-card"><div className="decision-card-head"><span>Recommended next step</span><ShieldCheck size={18}/></div><strong>{primary[0]}</strong><p>Start with a direct conversation. We will confirm the relevant requirements before any recruitment activity begins.</p><div className="decision-steps">{nextSteps.map((step,i)=><span key={step}><i>{i+1}</i>{step}</span>)}</div><Link href={primary[1]}>Start your enquiry <ArrowRight size={14}/></Link></aside></div></div></section><nav className="inner-nav" aria-label="Related pages"><div className="container"><span>Explore</span>{shortcuts.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div></nav></>
}
export function SectionHead({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy?:string;action?:React.ReactNode}){return <div className="section-head"><div><span className="eyebrow">{eyebrow}</span><h2 className="title">{title}</h2>{copy&&<p className="lead" style={{marginTop:18}}>{copy}</p>}</div>{action}</div>}
export function Disclaimer(){return <div className="notice">{availability}</div>}
export function TrustStrip(){return <section className="trust"><div className="container trust-grid">{["Licensed overseas recruitment company","Skilled, semi-skilled & general recruitment","Domestic recruitment specialists","Candidate screening & verification","Documentation & mobilisation support"].map(x=><div className="trust-item" key={x}><Check size={16}/>{x}</div>)}</div></section>}
export function JsonLd({data}:{data:object}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>}
